language: c
env:
  global:
     # You can uncomment this to explicitly choose an (old) version of the Arduino IDE
     #- ARDUINO_IDE_VERSION="1.8.7"
    - ADDITIONAL_URLS="https://adafruit.github.io/arduino-board-index/package_adafruit_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json,https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

jobs:
  include:
    - stage: "Build"
      name: "Feather M0"
      env: CORE="adafruit:samd" BOARD="adafruit:samd:adafruit_feather_m0"
    - name: "Arduino Zero"
      env: CORE="arduino:samd" BOARD="arduino:samd:mzero_bl"
    - name: "ESP32"
      env: CORE="esp32:esp32" BOARD="esp32:esp32:d32"
    - name: "STM32"
      env: CORE="STM32:stm32" BOARD="STM32:stm32:Nucleo_144:pnum=NUCLEO_F767ZI"
      script:
        - arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/stm32/EthernetHTTPSstm32
    - stage: "Deploy"
      if: branch = master AND tag is present
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "SSLClient.zip"
        skip_cleanup: true


install:
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/bin sudo sh
  - arduino-cli core update-index --additional-urls $ADDITIONAL_URLS
  - arduino-cli core install arduino:samd -v
  - arduino-cli core install $CORE -v --additional-urls $ADDITIONAL_URLS
  - mkdir -p $HOME/Arduino/libraries
  - rm -rf $HOME/Arduino/libraries/EthernetLarge
  - git clone https://github.com/OPEnSLab-OSU/EthernetLarge.git $HOME/Arduino/libraries/EthernetLarge
  - arduino-cli lib install "STM32duino STM32Ethernet"
  - arduino-cli lib install "PubSubClient"
  - ln -s $PWD $HOME/Arduino/libraries/.

script:
  - arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/EthernetHTTPS
  - arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/EthernetMultiHTTPS
  - arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/EthernetMQTT